# Generated by Django 6.1.1 on 2026-09-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_employe_a487d8_idx",
            old_name="notificatio_employe_c4b2a1_idx",
        ),
    ]
