# Generated by Django 6.1.1 on 2026-09-17 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0002_align_employee_csv_schema"),
        ("leaves", "0002_seed_leave_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("HOD", "Head of Department"),
                            ("APPROVER_1", "Approver 1"),
                            ("VC", "Vice-Chancellor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_actions",
                        to="employees.employee",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_actions",
                        to="leaves.leaveapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["application", "created_at"],
                        name="approvals_a_applica_7d3393_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ApproverAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("HOD", "Head of Department"),
                            ("APPROVER_1", "Approver 1"),
                            ("VC", "Vice-Chancellor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=150)),
                ("sub_department", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approver_assignments",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "department", "sub_department"],
                "indexes": [
                    models.Index(fields=["role"], name="approvals_a_role_f192c8_idx"),
                    models.Index(
                        fields=["employee"], name="approvals_a_employe_907f38_idx"
                    ),
                    models.Index(
                        fields=["department", "sub_department"],
                        name="approvals_a_departm_501316_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "department", "sub_department"),
                        name="uniq_approver_role_unit",
                    )
                ],
            },
        ),
    ]
