# Generated by Django 6.1.1 on 2026-09-17 09:14

from django.db import migrations, models


def dedupe_approver_assignments(apps, schema_editor):
    ApproverAssignment = apps.get_model('approvals', 'ApproverAssignment')
    vcs = list(ApproverAssignment.objects.filter(role='VC').order_by('pk'))
    for extra in vcs[1:]:
        extra.delete()

    seen = set()
    staff = ApproverAssignment.objects.filter(
        role__in=['APPROVER_1', 'APPROVER_2']
    ).order_by('pk')
    for row in staff:
        key = (row.role, row.employee_id, row.department)
        if key in seen:
            row.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0001_initial"),
        ("employees", "0002_align_employee_csv_schema"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="approverassignment",
            name="uniq_approver_role_unit",
        ),
        migrations.AlterField(
            model_name="approvalaction",
            name="step",
            field=models.CharField(
                choices=[
                    ("HOD", "Head of Department"),
                    ("APPROVER_1", "Approver 1"),
                    ("APPROVER_2", "Approver 2"),
                    ("VC", "Vice-Chancellor"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="approverassignment",
            name="role",
            field=models.CharField(
                choices=[
                    ("HOD", "Head of Department"),
                    ("APPROVER_1", "Approver 1"),
                    ("APPROVER_2", "Approver 2"),
                    ("VC", "Vice-Chancellor"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(dedupe_approver_assignments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="approverassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "HOD")),
                fields=("role", "department", "sub_department"),
                name="uniq_hod_role_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="approverassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "VC")),
                fields=("role",),
                name="uniq_vc_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="approverassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role__in", ["APPROVER_1", "APPROVER_2"])),
                fields=("role", "employee", "department"),
                name="uniq_staff_approver_role_employee_dept",
            ),
        ),
    ]
