# Generated by Django 6.1.1 on 2026-09-17 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0002_approver2_and_role_uniqueness"),
        ("employees", "0002_align_employee_csv_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeApprover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="as_personal_approver_1",
                        to="employees.employee",
                    ),
                ),
                (
                    "approver_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="as_personal_approver_2",
                        to="employees.employee",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_approver_map",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["employee__emp_id"],
                "indexes": [
                    models.Index(
                        fields=["approver_1"], name="approvals_e_approve_574893_idx"
                    ),
                    models.Index(
                        fields=["approver_2"], name="approvals_e_approve_c1f03d_idx"
                    ),
                ],
            },
        ),
    ]
