# Generated by Django 6.1.1 on 2026-09-17 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0003_employeeapprover"),
        ("employees", "0002_align_employee_csv_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeapprover",
            name="approver_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="as_personal_approver_1",
                to="employees.employee",
            ),
        ),
    ]
