# Generated by Django 6.1.1 on 2026-09-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_is_admin"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="account",
            new_name="accounts_ac_is_admi_430ea9_idx",
            old_name="accounts_ac_is_admi_7c9a2e_idx",
        ),
    ]
