# Generated by Django 6.1.1 on 2026-09-18 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_rename_accounts_ac_is_admi_7c9a2e_idx_accounts_ac_is_admi_430ea9_idx",
        ),
        ("employees", "0002_align_employee_csv_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_operator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["is_operator"], name="accounts_ac_is_oper_463ea1_idx"
            ),
        ),
    ]
