# Generated by Django 6.1.1 on 2026-09-17 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_align_employee_csv_schema"),
        ("leaves", "0002_seed_leave_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveapplication",
            name="chain_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FACULTY", "Faculty (HOD → VC)"),
                    ("STAFF", "Staff (Approver 1 → VC)"),
                    ("NONE", "Unrouted"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="current_step",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="waiting_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_approvals_waiting",
                to="employees.employee",
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapplication",
            index=models.Index(
                fields=["status", "waiting_on"], name="leaves_leav_status_407d09_idx"
            ),
        ),
    ]
