# Generated by Django 6.1.1 on 2026-09-17 06:38

from django.db import migrations, models


def backfill_requested_on(apps, schema_editor):
    LeaveApplication = apps.get_model('leaves', 'LeaveApplication')
    for application in LeaveApplication.objects.filter(requested_on__isnull=True):
        application.requested_on = application.created_at.date()
        application.save(update_fields=['requested_on'])


def unfill_requested_on(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_align_employee_csv_schema"),
        ("leaves", "0003_leaveapplication_chain_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaveapplication",
            options={"ordering": ["-requested_on", "-created_at"]},
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="external_key",
            field=models.CharField(blank=True, max_length=191, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="requested_on",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="source",
            field=models.CharField(
                choices=[
                    ("INTERNAL", "Applied in this system"),
                    ("IMPORTED", "Imported from university report"),
                ],
                db_index=True,
                default="INTERNAL",
                max_length=12,
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapplication",
            index=models.Index(fields=["source"], name="leaves_leav_source_df668f_idx"),
        ),
        migrations.RunPython(backfill_requested_on, unfill_requested_on),
    ]
