# Generated by Django 6.1.1 on 2026-09-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0004_alter_leaveapplication_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveapplication",
            name="session",
            field=models.CharField(
                choices=[
                    ("FULL_DAY", "Full day"),
                    ("FIRST_HALF", "First Half"),
                    ("SECOND_HALF", "Second Half"),
                ],
                default="FULL_DAY",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="days",
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
