# Generated by Django 6.1.1 on 2026-09-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0005_leaveapplication_session_alter_leaveapplication_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaveapplication",
            name="chain_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FACULTY", "Faculty (HOD → VC)"),
                    ("STAFF", "Staff (Approver 1 → Approver 2 → VC)"),
                    ("NONE", "Unrouted"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
    ]
