# Generated by Django 6.1.1 on 2026-09-18 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_align_employee_csv_schema"),
        ("leaves", "0006_approver2_and_role_uniqueness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaveapplication",
            name="source",
            field=models.CharField(
                choices=[
                    ("INTERNAL", "Applied in this system"),
                    ("IMPORTED", "Imported from university report"),
                    ("ASSIGNED", "Sanctioned by administration"),
                ],
                db_index=True,
                default="INTERNAL",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="LeaveCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("days", models.DecimalField(decimal_places=1, max_digits=6)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_credits",
                        to="employees.employee",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_leave_credits",
                        to="employees.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits",
                        to="leaves.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "leave_type", "year"],
                        name="leaves_leav_employe_9ee3ef_idx",
                    )
                ],
            },
        ),
    ]
